baseURL: "https://themisir.com/"
languageCode: "en-us"
title: "TheMisir"
theme: "paper"

author:
  email: "me@themisir.com"
  name: "Misir Jafarov"

params:
  twitter: "themisir"
  github: "themisir"
  instagram: "themisir0"

permalinks:
  posts: /:filename/

menu:
  main:
    - identifier: "archive"
      name: "Archive"
      url: "/posts"
      weight: 10
