baseURL: "https://themisir.com/"
languageCode: "en-us"
title: "Misir's Blog"
theme: "paper"
copyright: "Licensed under CC-BY-4.0 by Misir Jafarov, 2019-2023"

author:
  name: "Misir Jafarov"

params:
  github: "https://github.com/themisir"
  instagram: "https://instagram.com/themisir0"
  mastodon: "https://mastodon.social/@themisir"

  license:
    url: "https://creativecommons.org/licenses/by/4.0/"
    title: "CC-BY-4.0"

permalinks:
  posts: /:filename/
  essays: /essays/:filename/

taxonomies:
  category: "categories"
  series: "series"
  tag: "tags"

menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts"
      weight: 10
    - identifier: "essays"
      name: "Essays"
      url: "/essays"
      weight: 20
    - identifier: "random-gallery"
      name: "Gallery"
      url: "/galleries/random"
      weight: 30
    - identifier: "about"
      name: "About"
      url: "/about"
      weight: 40

markup:
  goldmark:
    renderer:
      unsafe: true
