baseURL: "https://themisir.com/"
languageCode: "en-us"
title: "TheMisir"
theme: "paper"

author:
  email: "me@themisir.com"
  name: "Misir Jafarov"

params:
  twitter: "themisir"
  github: "themisir"
  instagram: "themisir0"

permalinks:
  posts: /:filename/

menu:
  main:
    - identifier: "blog"
      name: "Blog"
      url: "/posts"
      weight: 10
    - identifier: "engineering"
      name: "Engineering"
      url: "/tags/engineering"
      weight: 20
    - identifier: "github"
      name: "Projects"
      url: "https://github.com/themisir?tab=repositories"
      weight: 30
    - identifier: "rss"
      name: "RSS"
      url: "/index.xml"
      weight: 100
