baseURL: "https://themisir.com/"
languageCode: "en-us"
title: "TheMisir"
theme: "paper"

author:
  email: "me@themisir.com"
  name: "Misir Jafarov"

params:
  twitter: "themisir"
  github: "themisir"
  instagram: "themisir0"

permalinks:
  posts: /:filename/
  essays: /essays/:filename/

menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts"
      weight: 10
    - identifier: "essays"
      name: "Essays"
      url: "/essays"
      weight: 20

markup:
  goldmark:
    renderer:
      unsafe: true
