baseURL: "https://themisir.com/"
languageCode: "en-us"
title: "TheMisir"
theme: "paper"
copyright: "Licensed under CC-BY-4.0 by Misir Jafarov, 2019-2023"

author:
  email: "me@themisir.com"
  name: "Misir Jafarov"

params:
  twitter: "themisir"
  github: "themisir"
  instagram: "themisir0"

  license:
    url: "https://creativecommons.org/licenses/by/4.0/"
    title: "CC-BY-4.0"

permalinks:
  posts: /:filename/
  essays: /essays/:filename/

taxonomies:
  category: "categories"
  series: "series"
  tag: "tags"

menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts"
      weight: 10
    - identifier: "essays"
      name: "Essays"
      url: "/essays"
      weight: 20
    - identifier: "about"
      name: "About"
      url: "/about"
      weight: 30

markup:
  goldmark:
    renderer:
      unsafe: true
