---
title: "Less is More"
date: 2023-02-18T03:00:00+04:00
tags:
  - unusual
  - engineering
  - science
images:
  - https://images.unsplash.com/photo-1466784828399-9a9921e8bdfd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80
---

This article is going to be a rant about the current state of ..., everything? At first, I started thinking about the bloated state of the technology, since tech is my primary source of inspration to find will to live. However, as I spend more time fiddling around, I realized  it's not just the tech that gets worse as it becomes bloated. The same principle applies to organizations, humans, life, society, politics, whatever you can think of. The more responsibility, the more power one gets, the more bloated, the more abusive it becomes.

Let's start from tech and I will probably find myself out writing about how much rooted our society did become as our understanding of world grew bigger than a simple human being can compershapnd. Web is one of the greatest innovation, discovery or invention depending on which point you're looking from. It let people share information without borders, it let knowledge to be more accessible. Well, depending on point in time you may or may not be fortunate enough to experience early days of the internet. I was one of the unfortunate pleasants since when my understanding of technology started forming, web already started becoming bloated, and everything seemed as "that's what it should look like". Everything felt like a "normal". That's what I used to see. That was how everything used to work, everything that I am aware of their existence.

It become okay to have monstrous platforms like facebook, google and others to have a greater control over what's going to be a new "normal" for people. They had a greater percentage of saying on the new ecosystem that's growing faster-and-faster as more users started using web. Today it's just a norm to have a social media profile to the point where, one's not having a social media account now being seem like an unusual, vague, weird behavior. Heck, even unborn babies nowadays have their social media accounts. And probably going to get publicity without any consent whatsoever, having their entire childhood being put publicly onto the wast ocean. Those babies are going to have rought time when their classmates find out their childhood photos online and starts pointing out onto something they found funny. You might say, that's okay. It might be totally alright for you or someone else to have that expereince. They might just laugh and move on with their life. However, the life is being experienced different by each human being. Just because you would be fine with those facts doesn't mean, your unborn kid wouldn't have some minor childhood traumas that might lead to major insecurities on their adulthoods. I am starting to respect people I have never heard of just because they decided to not put their kid's personal out there publicly. Why I have to feel respectful about them though? That should be a 🦆ing normal.

Privacy is a basic human right. Yet, for most they just ignore that privacy even exists. It become another "normal" to abuse our own and loved ones' privacy. It become a "normal" to not ask for a consent for any privacy abusing action.

Oh boy, have I been sidetracked a lot. I was not intended to go into privacy concerns, but as you can see the current state of technology & web can not be discussed without going into privacy. Let's step back before I start going over other nonsense arguments like "I don't need privacy because I have nothing to hide". It's like saying "I don't need free-speech, because I don't have anything to say".

# Web is bloated

I would like to take another look at the bloatness of web from a different angle. Let's talk about art. Web design to be exact. Website design become so bloated over the years that browsing the web without using loads of extensions literally become a burdensome. It's a requirement to have an [ad blocker](https://github.com/gorhill/uBlock) nowadays, whether you consider it ethical or not. Nowadays memes like "i watched a video between ads" are starting to feel more and more related to the reality itself. Sure, those companies need to increase their revenue in order to stay afloat, but, do you think they would stop when they reach out "enough" profitability? Heck no, in fact there's no "enough revenue". People don't care about the current state, they either look forward for an increase or decrease. If something goes up, it's better, they want more and more. What I am trying to say is if we don't step in and say something, those abusers won't stop when they reach enough profitability. They will abuse us more and more, they will abuse our time, our data, our norms, then they will abuse our values.

Nowadays when you have something clean, something simple, something that does just one thing, it seems unusual. People either take a weird looks or appreciate it like it's something unusual. That's how the web used to work back when it was owned by ordinary humans - us. That's how it used to be when there was not any financial incentive to shove every minor detail into users' eyes in order to get every bit of their attention.

Have ever tried reading any news article from their official website lately? How many popups did you encountered? I know, I know they need to be profitable, they need to get more paying customers to be profitable, but as I stated earlier, there's never "enough profitability". They won't ever stop and say, damn now that we have enough revenue we can start removing those annoying popups and let our customers have much better experience. It's not much different for the paying customers either. For those companies there's never enough, if someone decided to pay $, you can propably squeeze some percentage of them to get $$, try a bit harder and you'll get $$$. Did you become our paid member, great! Now, let me tell you about our premium membership which is the same thing but you'll pay a buck more to access some extra content that you will never ever check out. The story doesn't end there either. Are you happy with your premium membership? No? Sucks to be you mate, but hey at least now we have premium plus membership which is just exactly same thing but you'll have access to even more special content that you will never ever check out. But at least you'll have a golden badge after your name which you can brag out to your friends on social media.

# ... so we are

We - humans like bragging out. We like talking about our achievements. It is because of one of our survival instincts, our need for acceptance. Our ancestors needed to be accepted by others in order to live alongside with them, so they wouldn't die living alone on the forest. Eventually we have figured out a way to survive alone, without needing acceptance of others. However, our instincts haven't left us behind. We still live with the same desire of acceptance. We still seek approval from others, it hurts us emotionally when we get rejected. That hurt feeling used to be a good thing when we - humans were still trying to figure out how to live (at least that's we've been told). It formed our opinions on what's good and what's bad.

The cruel part however is that, nowadays our basic instincts are being abused to the fullest. The whole idea of social media is based on the fact that human will seek further approval by their peers. However, we don't have a built-in gauge telling us when we have enough approval. Therefore our opinions and instincts are formed on a fact that there will be never enough amount of approval. That's the whole reason why social media works. You will never feel enough level of approval, you will always want more. You will be motivated to post more for more engagement (likes, comments), more engagements = more approval. "Got a well received post? Great, Now create another one maybe it'll get a lot more. It didn't received enough appreciation huh? They don't know what a quality content looks like. Let's try better next time. More, more, more..." That's probably what's going on inside our inner dialogue.

That feedback loop does wonders for social media companies, and does even more wonderious for the consumerist community. Usually 90% of those communities are consumers of the content created by the other 10% members (source: i made it up). The more consumers means there's more incentive for "creators" to create more content for more approval. And for consumers it works well too. They will have more content to consume. Well, the content quality will suffer. But in exchange they will have more.

It's not just about the act of consuming either. How we consume content gets degraded as well over time. Why spend hours on a quality move, or reading something and diving deep into imaginary worlds when you can just get a small burst of happiness by watching 5-10 seconds of video clip. The quality doesn't matter anymore. For sure if you had spend hours to get that happiness, you would have had felt more fulfilled. However, over time brain gets used to near-instant gratification so much, it starts to not care about long term happiness. As a bonus since it doesn't take as much time, you can consume a lot more, give out a lot more feeling of  acceptance to those who seek it. In return they will feel more motivated to keep creating. It's such a well oiled machine that's hard to break of. One wants more content, the other wants more acceptance. None of them will stop when they receive "enough". There's never enough of something for us.

Less doesn't satisfy us, we seek more, more satisfaction, more acceptance, more rewards, more money, more power, more responsibility. In the end we get bloated, just like the tech we build that became just like us. It's not the tech that's the problem, it our own nature. We make the life terrible for us to live for. We - humans created all the cruelty of the world. We released all the gases out there that's going to cause warning over time. We accepted that to happen. Why? So we can get more of what we already getting. Sometimes it was the money, sometimes it was our power, sometimes it was our satisfaction we wanted more of.

We never stopped to wonder if we had enough. And the worst, we never wanted to have less. Maybe it's not about getting more of what we already had more than enough, but it was about spreading, having less of what we already have. Life itself works that way too. Try concentrating energy into a point and it will try its best to spread even. That's one of the founding factors of our universe known as entropy. Energy wants to spread away. Counterintuitively though, if all the energy were spread evenly across the universe, we wouldn't have been existed in the first place. Maybe it's all going the way it supposed to be. Maybe all the cruelity is just a way of universe to fix its small mistakes and way to spread energy more evenly. Nonetheless It all started with the big bang - the state where all the energy were stored on a small sphere. And suddenly it started bursting and energy started spreading across the universe as we know of (or imagine of). Maybe wanting more is just a natural way of eventually causing equalibrium by bursting out when things pass certain point of no-return?

So many questions, yet so few we know of. You see, we want more answers, I do at least. I am not satisfied with our understanding of universe, life, heck we don't ever know much about ourselves. That's distrubingly unsatisfying fact for me to accept. We don't have answers about the universe. We have assumptions, we believe in them or we don't. None of that matters because we will probably have even better assumptions we believe in. Science is all about finding better answers. Not "the answer", but getting closer and closer. Is that a cruel too? At this point I don't know. Science does good for humans one might say. That again depends on how you define the word "good". Is it good that we invented all those cruel technology we used to kill hundreds not thousands of people. I know this sounds stupid for sure. War has always been one of the leading factors of development. However, for a moment I would like to take another look from different point of view. Would it better if we knew much less. By learning more first we got more powerful over the nature, then ourselves, now we are in process of destroying our own home. And all we wanted is more...

Less is more. Is it though? I don't know, and probably, will never know either.

