name: Vale

on: [push, pull_request]
jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          vale_flags: "--glob=*.md"
          token: ${{secrets.VALE_GITHUB_TOKEN}}
